import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const DEST_DIR = path.resolve('src/content/knowledge');

// Pre-defined Elite Glossary for Initial Enrichment (Generated by Antigravity AI)
const GLOSSARY = [
    {
        title: "NPU (Neural Processing Unit)",
        category: "芯片架构",
        description: "专门为加速神经网络运算设计的处理器。相比 GPU，NPU 在处理 AI 推理任务（如图像识别、语音处理）时具有极高的能效比，是 AI PC 和智能手机实现‘全天候 AI’的关键。",
    },
    {
        title: "DVFS (动态电压频率调整)",
        category: "能效优化",
        description: "一种通过实时调整处理器运行电压和频率来降低功耗的技术。在负载较低时降低电压频率可呈平方级降低功耗，是移动设备续航优化的核心手段。",
    },
    {
        title: "Intel 18A",
        category: "半导体工艺",
        description: "英特尔推出的埃米级制程工艺（相当于 1.8nm）。引入了 RibbonFET 全环绕栅极架构和 PowerVia 背面供电技术，旨在重夺全球芯片能效与性能的巅峰。",
    },
    {
        title: "SOH (电池健康状态)",
        category: "电池技术",
        description: "State of Health，衡量电池相对于新电池时的衰减程度。通过 AI 算法预测 SOH 变化，能有效延长电动车和手机电池的使用寿命并预防热失控风险。",
    },
    {
        title: "PUE (电源使用效率)",
        category: "算力基础设施",
        description: "Power Usage Effectiveness，数据中心总能耗与 IT 设备能耗的比值。PUE 越接近 1.0，代表数据中心的冷却和配电损耗越低，能效越高。",
    },
    {
        title: "TDP (热设计功耗)",
        category: "硬件参数",
        description: "Thermal Design Power，代表处理器在重负载下产生的最大热量。它是散热器设计的基准。注意：TDP 并不等同于实际运行时的实时功耗。",
    },
    {
        title: "PPW (每瓦性能回报)",
        category: "能效评价",
        description: "Performance Per Watt，衡量在消耗单位功率时所能产出的性能。对于边缘侧 AI 和移动计算，PPW 是比单纯的峰值性能更重要的评价指标。",
    }
];

async function generate() {
    console.log(`🧠 AI Wiki Generator Activated`);

    if (!fs.existsSync(DEST_DIR)) fs.mkdirSync(DEST_DIR, { recursive: true });

    for (const entry of GLOSSARY) {
        const slug = entry.title.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-');
        const filePath = path.join(DEST_DIR, `${slug}.md`);

        const frontmatter = {
            title: entry.title,
            date: new Date(),
            category: entry.category,
            description: entry.description.slice(0, 100) + '...'
        };

        const content = `\n# ${entry.title}\n\n${entry.description}\n\n---\n*本条目由 GJNX AI 引擎自动挖掘并生成，旨在构建硅基能效通识大厦。*`;

        const fileContent = matter.stringify(content, frontmatter);
        fs.writeFileSync(filePath, fileContent);
        console.log(`✅ Wiki Entry Created: ${entry.title}`);
    }
}

generate();
